package golem:ts-fetch-example;

interface api {
  get-last-result: func() -> string;
  fetch-json: func(url: string) -> string;
}

world ts-fetch-example  {
  import golem:api/host@0.2.0;
  export api;
}
