package pack:name;

// See https://component-model.bytecodealliance.org/design/wit.html for more details about the WIT syntax

interface api {
  add: func(value: u64);
  get: func() -> u64;
  publish: func() -> result<_, string>;
  pause: func();
}

world component-name {
  import golem:api/host@0.2.0;

  export api;
}
